version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    #volumes:
    #  - ./client:/data
    environment:
      - API_URL=http://localhost:3000/

  server:
    build: ./server
    ports:
      - 3000:3000
      - 3001:3001
    #volumes:
    #  - ./server:/data
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=server-database

  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db